product-os/jellyfish-plugin-discourse

- jest.config.js
- lib/actions/action-integration-discourse-mirror-event.ts
- lib/actions/index.ts
- lib/cards/index.ts
- lib/index.ts
- lib/integrations/discourse.ts
- lib/integrations/index.ts
- lib/integrations/utils.ts
- test/integration/sync/discourse-mirror.spec.ts
- test/integration/sync/discourse-translate.spec.ts
- test/integration/sync/discourse.spec.ts
- test/integration/sync/webhooks/discourse/index.ts
- test/unit/actions/action-integration-discourse-mirror-event.spec.ts
- test/unit/index.spec.ts
- test/unit/integrations/discourse.spec.ts
- test/unit/integrations/utils.spec.ts
> Remove license headers

- Dockerfile.postgres
- docker-compose.yml
---
Set a number of postgres server options to optimize for test performance
> Optimize postgres for test performance

- package.json
- test/integration/discourse-translate.spec.ts
> Update @balena/jellyfish-worker from 18.4.7 to 18.5.0

- docker-compose.test.yml
> Set LOGLEVEL=error for sut

- Dockerfile.postgres
- docker-compose.yml
> Clean up postgres service

- lib/contracts/channel-discussion-threads.ts
- lib/contracts/index.ts
- lib/index.ts
- package.json
- test/integration/discourse-mirror.spec.ts
- test/integration/discourse-translate.spec.ts
- test/integration/discourse.spec.ts
- test/unit/index.spec.ts
Change-type: minor
---
Add new channel to display comments from blog discussion threads on the forums.
Depends on:
- https://github.com/balena-io-modules/skhema/pull/89
> Add blog discussion comment channel

- test/integration/webhooks/external-inbound-message/expected.json
- test/integration/webhooks/external-inbound-whisper-eventual-post-stream/expected.json
- test/integration/webhooks/external-inbound-whisper/expected.json
- test/integration/webhooks/inbound-attachment-file/expected.json
- test/integration/webhooks/inbound-attachment-image/expected.json
- test/integration/webhooks/inbound-delete-topic-no-user/expected.json
- test/integration/webhooks/inbound-delete-topic/expected.json
- test/integration/webhooks/inbound-edit-description/expected.json
- test/integration/webhooks/inbound-edit-title/expected.json
- test/integration/webhooks/inbound-emoji/expected.json
- test/integration/webhooks/inbound-message-attachment-file/expected.json
- test/integration/webhooks/inbound-message-attachment-image/expected.json
- test/integration/webhooks/inbound-message-delete-no-user-id/expected.json
- test/integration/webhooks/inbound-message-delete-undo/expected.json
- test/integration/webhooks/inbound-message-delete-user/expected.json
- test/integration/webhooks/inbound-message-delete/expected.json
- test/integration/webhooks/inbound-message-edit/expected.json
- test/integration/webhooks/inbound-null-name/expected.json
- test/integration/webhooks/inbound-null-user/expected.json
- test/integration/webhooks/inbound-preview/expected.json
- test/integration/webhooks/inbound-tag-tag/expected.json
- test/integration/webhooks/inbound-tag-untag/expected.json
- test/integration/webhooks/inbound-whisper-delete/expected.json
- test/integration/webhooks/inbound-whisper-edit/expected.json
- test/integration/webhooks/inbound-whisper-emoji/expected.json
- test/integration/webhooks/inbound-with-tag/expected.json
- test/integration/webhooks/inbound-with-tags/expected.json
- test/integration/webhooks/internal-inbound-message-whisper/expected.json
> Update translate tests

- package.json
- test/integration/discourse-mirror.spec.ts
- test/integration/discourse.spec.ts
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> Use autumndb instead of jellyfish-core

- repo.yml
> Fix upstreams in repo.yml

- lib/contracts/triggered-action-integration-discourse-mirror-event.ts
- package.json
- test/integration/discourse-mirror.spec.ts
- test/integration/discourse.spec.ts
- test/unit/integrations/discourse.spec.ts
> Bump internal deps

- package.json
- test/integration/discourse-translate.spec.ts
- test/integration/discourse.spec.ts
> Update @balena/jellyfish-worker from 21.2.12 to 22.0.0

- package.json
- test/integration/discourse.spec.ts
> Bump internal packages

- lib/integrations/discourse.ts
- package.json
> Update worker to 24

- Taskfile.yml
- package.json
- scripts/delete-test-data.js
Add script to clean up test data
created during CI.
> Add test data cleanup script

- lib/integrations/discourse.ts
- test/integration/webhooks/external-inbound-message/expected.json
- test/integration/webhooks/external-inbound-whisper-eventual-post-stream/expected.json
- test/integration/webhooks/external-inbound-whisper/expected.json
- test/integration/webhooks/inbound-attachment-file/expected.json
- test/integration/webhooks/inbound-attachment-image/expected.json
- test/integration/webhooks/inbound-delete-topic-no-user/expected.json
- test/integration/webhooks/inbound-delete-topic/expected.json
- test/integration/webhooks/inbound-edit-description/expected.json
- test/integration/webhooks/inbound-edit-title/expected.json
- test/integration/webhooks/inbound-emoji/expected.json
- test/integration/webhooks/inbound-message-attachment-file/expected.json
- test/integration/webhooks/inbound-message-attachment-image/expected.json
- test/integration/webhooks/inbound-message-delete-no-user-id/expected.json
- test/integration/webhooks/inbound-message-delete-undo/expected.json
- test/integration/webhooks/inbound-message-delete-user/expected.json
- test/integration/webhooks/inbound-message-delete/expected.json
- test/integration/webhooks/inbound-message-edit/expected.json
- test/integration/webhooks/inbound-null-name/expected.json
- test/integration/webhooks/inbound-null-user/expected.json
- test/integration/webhooks/inbound-preview/expected.json
- test/integration/webhooks/inbound-tag-tag/expected.json
- test/integration/webhooks/inbound-tag-untag/expected.json
- test/integration/webhooks/inbound-whisper-delete/expected.json
- test/integration/webhooks/inbound-whisper-edit/expected.json
- test/integration/webhooks/inbound-whisper-emoji/expected.json
- test/integration/webhooks/inbound-with-tag/expected.json
- test/integration/webhooks/inbound-with-tags/expected.json
- test/integration/webhooks/internal-inbound-message-whisper/expected.json
> Set data.integration_source on synced contracts

- package.json
- test/integration/discourse-translate.spec.ts
> Update worker to 3.0.11

- lib/contracts/channel-discussion-threads.ts
- lib/contracts/index.ts
- lib/contracts/triggered-action-integration-discourse-mirror-event.ts
- lib/contracts/triggered-action-integration-discourse-mirror-thread.ts
- lib/contracts/view-all-forum-threads.ts
- lib/integrations/discourse.ts
- package.json
- test/integration/discourse.spec.ts
> Drop jellyfish-types

- package.json
- test/integration/index.spec.ts
- test/integration/mirror.spec.ts
- test/integration/translate.spec.ts
> Drop plugin-product-os

- lib/actions/action-integration-discourse-mirror-event.ts
- lib/index.ts
- package.json
- test/integration/index.spec.ts
- test/integration/mirror.spec.ts
- test/integration/translate.spec.ts
- test/unit/index.spec.ts
Signed-off-by: Josh Bowling <josh@monarci.com>
> Drop plugin-default

- package.json
- test/integration/mirror.spec.ts
This brings in a major change to how AutumnDB handles sessions.
See product-os/autumndb#1363
Change-type: major
Signed-off-by: Lucian Buzzo <lucian.buzzo@gmail.com>
> Upgrade to worker v32.x and AutumnDB v21.x

- package.json
Signed-off-by: Josh Bowling <josh@monarci.com>
> Update worker to 33.0.10

- .github/workflows/codeql-analysis.yml
- docker-compose.test.yml
- docker-compose.yml
- jest.config.js
- jest.config.json
Signed-off-by: Josh Bowling <josh@monarci.com>
> CI: Use JSON for Jest config

- package.json
- scripts/test-integration.sh
> Bump internal dependencies
